/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isabe
 */
import javax.swing.JOptionPane;
public class Employee_edit_gui extends javax.swing.JFrame {

    /**
     * Creates new form Employee_edit_gui
     */
    public Employee_edit_gui() {
        initComponents();
        if(editing == true){
            setInitialText();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeNameField = new javax.swing.JTextField();
        employeeAgeLabel = new javax.swing.JLabel();
        employeeAgeField = new javax.swing.JTextField();
        employeeWageLabel = new javax.swing.JLabel();
        employeeWageField = new javax.swing.JTextField();
        employeeWageLabel1 = new javax.swing.JLabel();
        employeeTimeField = new javax.swing.JTextField();
        btnSave = new javax.swing.JToggleButton();
        btnCancel1 = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        employeeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeNameLabel.setText("Name: ");

        employeeNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        employeeAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeAgeLabel.setText("Age:");

        employeeAgeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        employeeWageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeWageLabel.setText("Wage: ");

        employeeWageField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        employeeWageLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeWageLabel1.setText("Time Worked: ");

        employeeTimeField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(employeeWageLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeTimeField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeeWageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeeWageField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeNameLabel)
                                    .addComponent(employeeAgeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeAgeField)
                                    .addComponent(employeeNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNameLabel)
                    .addComponent(employeeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeAgeLabel)
                    .addComponent(employeeAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeWageLabel)
                    .addComponent(employeeWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeWageLabel1)
                    .addComponent(employeeTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 170));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        btnCancel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        setSize(new java.awt.Dimension(289, 273));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String iName = employeeNameField.getText();
        int iAge = 0;
        double iWage = 0;
        double iTW = 0;
        boolean validInput;
        try{
            iAge = Integer.parseInt(employeeAgeField.getText());
            iWage = Double.parseDouble(employeeWageField.getText());
            iTW = Double.parseDouble(employeeTimeField.getText());
            validInput = true;
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid Input");
            validInput = false;
        }
        if(validInput){
            if(editing == true){
                Employee editing_employee = Financial.getEmployees().get(eIndex);
                editing_employee.setName(iName);
                editing_employee.setAge(iAge);
                editing_employee.setWage(iWage);
                editing_employee.setTimeWorked(iTW);
                editing = false;
                this.hide();
            }else{
                Employee newEmployee = new Employee(iName, iAge, iWage, iTW);
                Financial.addEmployee(newEmployee);
                this.hide();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static boolean editing = false;
    public static int eIndex;
    
    private void setInitialText(){
        Employee employee_i = Financial.getEmployees().get(eIndex);
        employeeNameField.setText(employee_i.getName());
        employeeAgeField.setText(String.valueOf(employee_i.getAge()));
        employeeWageField.setText(String.valueOf(employee_i.getWage()));
        employeeTimeField.setText(String.valueOf(employee_i.getTimeWorked()));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_edit_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_edit_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_edit_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_edit_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_edit_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancel1;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JTextField employeeAgeField;
    private javax.swing.JLabel employeeAgeLabel;
    private javax.swing.JTextField employeeNameField;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTextField employeeTimeField;
    private javax.swing.JTextField employeeWageField;
    private javax.swing.JLabel employeeWageLabel;
    private javax.swing.JLabel employeeWageLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
