
import java.util.ArrayList;
import java.util.LinkedList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isabe
 */
import java.util.Scanner;
import java.io.*;
import javax.swing.*;

public class Teashop_gui extends javax.swing.JFrame {
    /**
     * Creates new form teashop_gui
     */
    public Teashop_gui() {
        initComponents();
        readSaveInfo();
        customerList.setModel(getCustomerList());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membershipTrueFalse = new javax.swing.ButtonGroup();
        saleMembership = new javax.swing.ButtonGroup();
        mainTabbedPane = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        tsLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        employeeTab = new javax.swing.JPanel();
        customerTab = new javax.swing.JPanel();
        btnModCustomer = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList<>();
        allCustomersLabel = new javax.swing.JLabel();
        itemTab = new javax.swing.JPanel();
        currentItemsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        btnModItem = new javax.swing.JButton();
        btnDelItem = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        saleTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        saleItemList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        finalSaleList = new javax.swing.JList<>();
        btnAddSale = new javax.swing.JButton();
        btnRemoveSale = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        memberBtnPanel = new javax.swing.JPanel();
        memberLabel = new javax.swing.JLabel();
        btnMemberTrue = new javax.swing.JRadioButton();
        btnMemberFalse = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        reportTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tea Shop");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        tsLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        tsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tsLabel.setText("Tea Shop");

        welcomeLabel.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/teacup.png"))); // NOI18N

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconLabel)
                .addGap(18, 18, 18)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tsLabel))
                    .addComponent(welcomeLabel))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Home", homeTab);

        javax.swing.GroupLayout employeeTabLayout = new javax.swing.GroupLayout(employeeTab);
        employeeTab.setLayout(employeeTabLayout);
        employeeTabLayout.setHorizontalGroup(
            employeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        employeeTabLayout.setVerticalGroup(
            employeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Employees", employeeTab);

        btnModCustomer.setText("Edit Customer");
        btnModCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCustomerActionPerformed(evt);
            }
        });

        btnAddCustomer.setText("New Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Delete Customer");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        customerList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(customerList);

        allCustomersLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allCustomersLabel.setText("All Current Customers");

        javax.swing.GroupLayout customerTabLayout = new javax.swing.GroupLayout(customerTab);
        customerTab.setLayout(customerTabLayout);
        customerTabLayout.setHorizontalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(customerTabLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(allCustomersLabel)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        customerTabLayout.setVerticalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTabLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(allCustomersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerTabLayout.createSequentialGroup()
                        .addComponent(btnModCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddCustomer)))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Customers", customerTab);

        currentItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentItemsLabel.setText("All Current Items");

        itemList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(itemList);

        btnModItem.setText("Edit Item");
        btnModItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModItemActionPerformed(evt);
            }
        });

        btnDelItem.setText("Delete Item");
        btnDelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelItemActionPerformed(evt);
            }
        });

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemTabLayout = new javax.swing.GroupLayout(itemTab);
        itemTab.setLayout(itemTabLayout);
        itemTabLayout.setHorizontalGroup(
            itemTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelItem, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(itemTabLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(currentItemsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemTabLayout.setVerticalGroup(
            itemTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(currentItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(itemTabLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnModItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddItem)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Items", itemTab);

        saleItemList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(saleItemList);

        finalSaleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(finalSaleList);

        btnAddSale.setText("Add To Sale ->");
        btnAddSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaleActionPerformed(evt);
            }
        });

        btnRemoveSale.setText("<- Remove");
        btnRemoveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSaleActionPerformed(evt);
            }
        });

        btnReceipt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReceipt.setText("Print Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        memberBtnPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        memberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        memberLabel.setText("Membership");

        saleMembership.add(btnMemberTrue);
        btnMemberTrue.setText("True");
        btnMemberTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberTrueActionPerformed(evt);
            }
        });

        saleMembership.add(btnMemberFalse);
        btnMemberFalse.setSelected(true);
        btnMemberFalse.setText("False");

        javax.swing.GroupLayout memberBtnPanelLayout = new javax.swing.GroupLayout(memberBtnPanel);
        memberBtnPanel.setLayout(memberBtnPanelLayout);
        memberBtnPanelLayout.setHorizontalGroup(
            memberBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberBtnPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(memberBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberLabel)
                    .addGroup(memberBtnPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(memberBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMemberFalse)
                            .addComponent(btnMemberTrue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        memberBtnPanelLayout.setVerticalGroup(
            memberBtnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberBtnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(memberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMemberTrue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMemberFalse)
                .addContainerGap())
        );

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear Order");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saleTabLayout = new javax.swing.GroupLayout(saleTab);
        saleTab.setLayout(saleTabLayout);
        saleTabLayout.setHorizontalGroup(
            saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saleTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(saleTabLayout.createSequentialGroup()
                                .addComponent(btnAddSale)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnRemoveSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(memberBtnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(saleTabLayout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReceipt)))
                .addGap(31, 31, 31))
        );
        saleTabLayout.setVerticalGroup(
            saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(saleTabLayout.createSequentialGroup()
                        .addComponent(btnAddSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveSale)
                        .addGap(28, 28, 28)
                        .addComponent(memberBtnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(saleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReceipt)
                    .addComponent(btnClear))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("New Sale", saleTab);

        javax.swing.GroupLayout reportTabLayout = new javax.swing.GroupLayout(reportTab);
        reportTab.setLayout(reportTabLayout);
        reportTabLayout.setHorizontalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        reportTabLayout.setVerticalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Reports", reportTab);

        getContentPane().add(mainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));

        setSize(new java.awt.Dimension(537, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        Customer_edit_gui.editing = false;
        new Customer_edit_gui().setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        customerList.setModel(getCustomerList());
        itemList.setModel(getItemList());
        saleItemList.setModel(getItemDisplay());
        finalSaleList.setModel(getSaleItems());
        writeSaveInfo();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        if(customerList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Please select a customer to delete.");
        }
        else{
            Customer customer_i = Financial.getCustomers().get(customerList.getSelectedIndex());
            int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete "+ customer_i.getName(), "Delete Confirmation",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
               Financial.removeCustomer(customer_i);
               customerList.setModel(getCustomerList()); //update customer list
            }else if (result == JOptionPane.NO_OPTION){
               //do nothing
            }
        }
        
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnModCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCustomerActionPerformed
        if(customerList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Please select a customer to edit.");
        }else{
            Customer_edit_gui.cIndex = customerList.getSelectedIndex();
            Customer_edit_gui.editing = true;
            new Customer_edit_gui().setVisible(true);
        }
    }//GEN-LAST:event_btnModCustomerActionPerformed

    //handle item options
    private void btnDelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelItemActionPerformed
        if(itemList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Please select an item to delete.");
        }
        else{
            Item item_i = Financial.getItems().get(itemList.getSelectedIndex());
            int result = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete "+ item_i.getName(), "Delete Confirmation",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
               Financial.removeItem(item_i);
               customerList.setModel(getCustomerList()); //update customer list
            }else if (result == JOptionPane.NO_OPTION){
               //do nothing
            }
        }
    }//GEN-LAST:event_btnDelItemActionPerformed

    private void btnModItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModItemActionPerformed
        if(itemList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Please select an item to edit.");
        }else{
            Item_edit_gui.iIndex = itemList.getSelectedIndex();
            Item_edit_gui.editing = true;
            new Item_edit_gui().setVisible(true);
        }
    }//GEN-LAST:event_btnModItemActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        new Item_edit_gui().setVisible(true);   
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnAddSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaleActionPerformed
        if(saleItemList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an item to add to the order.");
        }else{
            Item item_i = Financial.getItems().get(saleItemList.getSelectedIndex());
            Financial.newSale.addOrderItem(item_i);
            finalSaleList.setModel(getSaleItems());
        }
    }//GEN-LAST:event_btnAddSaleActionPerformed

    private void btnRemoveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSaleActionPerformed
        if(finalSaleList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an order item to remove.");
        }else{
            Item item_i = Financial.newSale.order.get(finalSaleList.getSelectedIndex());
            Financial.newSale.order.remove(item_i);
            finalSaleList.setModel(getSaleItems());
        }
    }//GEN-LAST:event_btnRemoveSaleActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        if(Financial.getItems().isEmpty()){
            JOptionPane.showMessageDialog(null, "Your order is empty. Please add items to this order.");
        }
        else{
            Display_gui.isMember = btnMemberTrue.isSelected();
            Display_gui.displayType = 0;
            new Display_gui().setVisible(true);
        }
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void btnMemberTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMemberTrueActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Financial.newSale.order.clear();
        btnMemberFalse.setSelected(true);
        finalSaleList.setModel(getSaleItems());
    }//GEN-LAST:event_btnClearActionPerformed

    
    public static DefaultListModel getCustomerList(){
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<Financial.getCustomers().size();i++){
            Customer customer_i = Financial.getCustomers().get(i);
            String thisCustomer = ("Name: "+customer_i.getName()+", ID: "+customer_i.getID()+", Membership: "+ customer_i.isMember());
            model.addElement(thisCustomer);
        }
        return model;
    }
    public static DefaultListModel getItemList(){
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<Financial.getItems().size();i++){
            Item item_i = Financial.getItems().get(i);
            String thisItem = ("Name: "+item_i.getName()+", Number: "+item_i.getNumber()+", Cost: $"+ item_i.getCost());
            model.addElement(thisItem);
        }
        return model;
    }
    public static DefaultListModel getItemDisplay(){
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<Financial.getItems().size();i++){
            Item item_i = Financial.getItems().get(i);
            String thisItem = (item_i.getName() + ", $"+ item_i.getCost());
            model.addElement(thisItem);
        }
        return model;
    }
    public static DefaultListModel getSaleItems(){
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<Financial.newSale.order.size();i++){
            Item item_i = Financial.newSale.order.get(i);
            String thisItem = (item_i.getName() + ", $"+ item_i.getCost());
            model.addElement(thisItem);
        }
        return model;
    }
    
    //Methods for reading and writing save information
    public static void readSaveInfo(){
        readCustomerInfo();
        readItemInfo();
    }
    public static void writeSaveInfo(){
        writeCustomerInfo();
        writeItemInfo();
    }
    //read information methods
    public static void readCustomerInfo(){
        //read in saved customers, items, etc.
        try{
            //read save info for customers
            File customerFile = new File("customers.csv");
            FileReader Cfr = new FileReader(customerFile);
            BufferedReader Cbr = new BufferedReader(Cfr);
            
            String line = "";
            String[] c;
            while ((line = Cbr.readLine()) != null){
                c = line.split(",");
                String name = c[0];
                int id = Integer.parseInt(c[1]);
                boolean b = Boolean.parseBoolean(c[2]);
                Customer newCustomer = new Customer(name, id, b);
                Financial.addCustomer(newCustomer);
            }
            Cbr.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "There was an error reading saved information.");
        }
    }
    public static void readItemInfo(){
        //read in saved customers, items, etc.
        try{
            //read save info for customers
            FileReader fr = new FileReader(new File("items.csv"));
            BufferedReader br = new BufferedReader(fr);
            
            String line = "";
            String[] c;
            while ((line = br.readLine()) != null){
                c = line.split(",");
                String name = c[0];
                double cost = Double.parseDouble(c[1]);
                int num = Integer.parseInt(c[2]);
                Item newItem = new Item(name, cost, num);
                Financial.addItem(newItem);
            }
            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "There was an error reading saved information.");
        }
    }
    //write information methods
    private static void writeCustomerInfo(){
        try{         
            //update customer save file
            File customerFile = new File("customers.csv");
            BufferedWriter Cbf = new BufferedWriter(new FileWriter(customerFile));

            LinkedList<Customer> customers = Financial.getCustomers();
            for (int i=0;i<customers.size();i++){
                String row = "";
                Customer customer_i = customers.get(i);
                String cName = customer_i.getName();
                String cID = String.valueOf(customer_i.getID());
                String isMember = String.valueOf(customer_i.isMember());

                row = cName + "," + cID + "," +isMember + "\n";
                Cbf.write(row);
            }
            Cbf.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error saving information.");
        }
        
    }
    private static void writeItemInfo(){
        try{         
            //update customer save file
            File itemFile = new File("items.csv");
            BufferedWriter Cbf = new BufferedWriter(new FileWriter(itemFile));

            LinkedList<Item> items = Financial.getItems();
            for (int i=0;i<items.size();i++){
                String row = "";
                Item item_i = items.get(i);
                String iName = item_i.getName();
                String iCost = String.valueOf(item_i.getCost());
                String iNum = String.valueOf(item_i.getNumber());

                row = iName + "," + iCost + "," +iNum + "\n";
                Cbf.write(row);
            }
            Cbf.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error saving information.");
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //read and mofidy file information
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teashop_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teashop_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teashop_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teashop_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teashop_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allCustomersLabel;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelItem;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JRadioButton btnMemberFalse;
    private javax.swing.JRadioButton btnMemberTrue;
    private javax.swing.JButton btnModCustomer;
    private javax.swing.JButton btnModItem;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnRemoveSale;
    private javax.swing.JLabel currentItemsLabel;
    private javax.swing.JList<String> customerList;
    private javax.swing.JPanel customerTab;
    private javax.swing.JPanel employeeTab;
    private javax.swing.JList<String> finalSaleList;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JList<String> itemList;
    private javax.swing.JPanel itemTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel memberBtnPanel;
    private javax.swing.JLabel memberLabel;
    private javax.swing.ButtonGroup membershipTrueFalse;
    private javax.swing.JPanel reportTab;
    private javax.swing.JList<String> saleItemList;
    private javax.swing.ButtonGroup saleMembership;
    private javax.swing.JPanel saleTab;
    private javax.swing.JLabel tsLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
