/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isabe
 */
import java.util.ArrayList;
public class Display_gui extends javax.swing.JFrame {

    /**
     * Creates new form Display_gui
     */
    public Display_gui() {
        initComponents();
        setDisplayCode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTxtArea = new javax.swing.JTextArea();
        displayBtn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        displayTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        displayTitle.setText("jLabel1");

        displayTxtArea.setEditable(false);
        displayTxtArea.setColumns(20);
        displayTxtArea.setRows(5);
        jScrollPane1.setViewportView(displayTxtArea);

        displayBtn.setText("OK");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayBtn)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(displayTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(displayTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBtn)
                    .addComponent(btnCancel))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 342));

        setSize(new java.awt.Dimension(264, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //add this sale to all sales
        if(displayType == 0){
            Financial.allSales.add(thisSale);
            thisSale = 0;
            Financial.newSale.order.clear();
        }
        isMember = false;
        this.hide();
    }//GEN-LAST:event_displayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //0=receipt, 1=sale report, 2=employee payroll
    public static int displayType;
    public static int employeeInfoNum;
    public static boolean isMember;
    public static double thisSale;
    
    private void setDisplayCode(){
        //update components
        if(displayType == 0){ //if receipt
            displayTitle.setText("Receipt");
            btnCancel.setVisible(true);
            String receiptTxt = "";
            for (Item order : Financial.newSale.order) {
                receiptTxt = receiptTxt+(order.getName()+"  $" +order.getCost()+"\n");
            }
            receiptTxt = receiptTxt+"-----------------\n";
            thisSale = Financial.newSale.getTotalCost(isMember);
            receiptTxt = receiptTxt+(String.format("%.2f", thisSale));
            displayTxtArea.setText(receiptTxt);
        }else if(displayType == 1){ //if sales report
            displayTitle.setText("Sale Report");
            btnCancel.setVisible(false);
            String saleReport = "";
            for(int i=0;i<Financial.allSales.size();i++){
                saleReport = saleReport+"Sale of: $" +(String.format("%.2f", Financial.allSales.get(i)))+"\n";
            }
            saleReport = saleReport+"With a total of: "+(String.format("%.2f",Financial.getTotalProfit()));
            displayTxtArea.setText(saleReport);
        }else if(displayType == 2){ //if payroll
            displayTitle.setText("Employee Payroll Report");  
            btnCancel.setVisible(false);
            String payrollReport = "";
            for (Employee employee : Financial.getEmployees()) {
                payrollReport = payrollReport+employee.getName()+" earned $"+employee.getPay()+"\n";
            }
            payrollReport = payrollReport+"-----------------\nTotal expenses: $"+Financial.getTotalExpenses();
            displayTxtArea.setText(payrollReport);
        }else if(displayType == 3){ //if employee is viewing info
            displayTitle.setText("Employee Information");  
            btnCancel.setVisible(false);
            Employee thisEmp = Financial.getEmployees().get(employeeInfoNum);
            String employeeInfoTxt = "Name: "+thisEmp.getName()+"\nAge: "+thisEmp.getAge()+"\nWage: "+thisEmp.getWage()+"\nTime Worked: "+thisEmp.getTimeWorked();
            displayTxtArea.setText(employeeInfoTxt);
        }else if(displayType == 4){ //if employee is getting pay
            displayTitle.setText("Employee Pay");  
            btnCancel.setVisible(true);
            Employee thisEmp = Financial.getEmployees().get(employeeInfoNum);
            String payText = "Pay for "+thisEmp.getName()+" is $"+thisEmp.getPay()+"\nAfter working for \n"+thisEmp.getTimeWorked()+" hours at "+thisEmp.getWage()+"$/hr";
            displayTxtArea.setText(payText);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel displayTitle;
    private javax.swing.JTextArea displayTxtArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
